### ISSUE TITLE
Improving User Experience with a Move2Kube Cheatsheet

### ISSUE THREAD

**Issue by lakshay-nasa** [konveyor/move2kube-website#108]
**Is your feature request related to a problem? Please describe.**
Yes, although the commands and syntaxes for Move2Kube are available online, users may find it difficult to remember or reference them frequently. This can reduce productivity, so it's better to have them all in one place.

**Describe the solution you'd like**
Add a comprehensive Move2Kube cheatsheet that includes all the features, commands, and syntaxes used in the project.

**Describe alternatives you've considered**
Creating a tutorial or relying on external resources, but a cheatsheet would be more convenient and efficient.

**Additional context**
Move2Kube cheatsheet would be a valuable addition to the project documentation, as it would provide users with a quick reference guide for all the features, commands, and syntaxes used in the project.

**Comment by kmehant** [comment]
@HarikrishnanBalagopal I think we can close this.
