### ISSUE TITLE
Feat: Support adding Summary as an input while triggering a release

### ISSUE THREAD

**Issue by kmehant** [konveyor/move2kube-website#92]
**Is your feature request related to a problem? Please describe.**
It would be great to have an option to input summary while triggering a release.

**Describe the solution you'd like**
Add input field to move2kube release panel

**Describe alternatives you've considered**

**Additional context**

**Comment by ashokponkumar** [comment]
For now, after the release is created, we can manually edit the release with the description. It will be easier this way, since the user will have info on what has gone into the release from the auto generated logs.

**Comment by HarikrishnanBalagopal** [comment]
> For now, after the release is created, we can manually edit the release with the description. It will be easier this way, since the user will have info on what has gone into the release from the auto generated logs.

The feature is more for our own use rather than OSSF requirement.

**Comment by kmehant** [comment]
@ashokponkumar Changelog and everything will still be there, along with it, additionally we will have a summary written by the releaser.

**Comment by ashokponkumar** [comment]
Yes, I am just wondering about the flow. Which flow will be easiest for a release engineer to author the description.

**Comment by kmehant** [comment]
oh, got it!!

**Comment by HarikrishnanBalagopal** [comment]
Yes I think you are right, it will be easier to write the summary by looking at the change log once the draft release has been created.
